### PR TITLE
API doc

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by hlapp** [comment]
As two side comments (I'm aware they're not directly related to what this pull request is about) I think we'll want to create `@phenoscape.org` aliases as contact addresses than using individual institutional addresses as contacts. Second is, I notice that the citations for the homology evidence are not linked. Not sure whether that's intentional or whether there's no target to link them too, but it's not great from a user's perspective.

**Comment by balhoff** [comment]
Currently these are only entered as text. I agree a link would be better.

**Comment by balhoff** [comment]
Can you configure those emails aliases? We used to have at least one and now I don't remember how it was set up.

**Comment by hlapp** [comment]
I can configure phenoscape.org email aliases. Unfortunately, they seem to need to go to a single recipient address, but if that's not a limitation, remind me which ones we need.

**Pull request merged**
