### PR TITLE
Update entity/presence/evidence service to work with relation graphs

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Test 1:

taxon: http://purl.obolibrary.org/obo/VTO_0039086
entity: http://purl.obolibrary.org/obo/UBERON_0000468
limit: 20
offset: 0
tital: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0039086&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 91
}
```

New KB:
```
curl -X GET "http://localhost:8082/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0039086&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":141}
```

**Comment by Shalsh23** [comment]
Test 2:

taxon: http://purl.obolibrary.org/obo/VTO_0039086
entity: http://purl.obolibrary.org/obo/UBERON_0000468
limit: 5
offset: 0
total: false

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0039086&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468&limit=5&offset=0&total=false" -H "accept: application/json"
```
```
{
  "results": [
    {
      "description": "2nd pre-ethmoid: absent",
      "matrix": {
        "@id": "http://www.worldcat.org/oclc/612613233",
        "label": "Siebert (1987)"
      },
      "character": {
        "@id": "http://purl.org/phenoscape/uuid/bb6ffadb-2b49-42d8-bbc1-8d41ee478ecb",
        "label": "2nd pre-ethmoid"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2002023%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2002023%3E%29",
        "label": "second preethmoid absent"
      },
      "@id": "http://purl.org/phenoscape/uuid/b9dcf663-0022-4a41-86ce-5f5c16212963"
    },
    {
      "description": "Absence of basibranchial 1: absent",
      "matrix": {
        "@id": "http://www.worldcat.org/oclc/612613233",
        "label": "Siebert (1987)"
      },
      "character": {
        "@id": "http://purl.org/phenoscape/uuid/c11e3e7e-f5fc-4151-a63a-aad5d44a26b6",
        "label": "Absence of basibranchial 1"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000467%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001223%3E%29%29",
        "label": "basibranchial 1 bone present"
      },
      "@id": "http://purl.org/phenoscape/uuid/5a214f1c-6ebe-4364-afca-88863f82c632"
    },
    {
      "description": "Absence of basihyal tooth plate: present",
      "matrix": {
        "@id": "http://www.worldcat.org/oclc/612613233",
        "label": "Siebert (1987)"
      },
      "character": {
        "@id": "http://purl.org/phenoscape/uuid/276475a9-d539-49af-bb44-7e45954753bf",
        "label": "Absence of basihyal tooth plate"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001648%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001648%3E%29",
        "label": "basihyal tooth plate absent"
      },
      "@id": "http://purl.org/phenoscape/uuid/cfe17fc0-5171-4fbf-8d09-18e00dc7c498"
    },
    {
      "description": "Absence of epibranchial I and II uncinate processes: present",
      "matrix": {
        "@id": "http://www.worldcat.org/oclc/612613233",
        "label": "Siebert (1987)"
      },
      "character": {
        "@id": "http://purl.org/phenoscape/uuid/228c9066-2e19-457f-a74c-46ceb954b792",
        "label": "Absence of epibranchial I and II uncinate processes"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001796%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001796%3E%29",
        "label": "epibranchial 2 bone uncinate process absent"
      },
      "@id": "http://purl.org/phenoscape/uuid/1a9173a4-04a5-433c-8e7b-19ae985ee1ba"
    },
    {
      "description": "Absence of epibranchial I and II uncinate processes: present",
      "matrix": {
        "@id": "http://www.worldcat.org/oclc/612613233",
        "label": "Siebert (1987)"
      },
      "character": {
        "@id": "http://purl.org/phenoscape/uuid/228c9066-2e19-457f-a74c-46ceb954b792",
        "label": "Absence of epibranchial I and II uncinate processes"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001797%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001797%3E%29",
        "label": "epibranchial 1 bone uncinate process absent"
      },
      "@id": "http://purl.org/phenoscape/uuid/1a9173a4-04a5-433c-8e7b-19ae985ee1ba"
    }
  ]
}
```

New KB:
```
 curl -X GET "http://localhost:8082/entity/presence/e
vidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0039086&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468&limit=5&offset=0&total=false
" -H "accept: application/json"
```
```
{"results":[{"description":"2nd pre-ethmoid: absent","matrix":{"@id":"http://www.worldcat.org/oclc/612613233","label":"Siebert (1987)"},"character":{"@id":"http://purl.org/phenoscape/uuid/efd4fbe0-a004-4667-b4c4-3acfe999ae9c","label":"2nd pre-ethmoid"},"phenotype":{"@id":"http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2002023%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2002023%3E%29","label":"second preethmoid absent"},"@id":"http://purl.org/phenoscape/uuid/7fc4f4bc-43d2-4848-8752-536334ceffee"},{"description":"Absence of basibranchial 1: absent","matrix":{"@id":"http://www.worldcat.org/oclc/612613233","label":"Siebert (1987)"},"character":{"@id":"http://purl.org/phenoscape/uuid/363e6858-a580-4b39-bd43-50a36f71003d","label":"Absence of basibranchial 1"},"phenotype":{"@id":"http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000467%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001223%3E%29%29","label":"basibranchial 1 bone present"},"@id":"http://purl.org/phenoscape/uuid/ce1663a6-ac4e-4d45-a703-042ac90426c8"},{"description":"Absence of basihyal tooth plate: present","matrix":{"@id":"http://www.worldcat.org/oclc/612613233","label":"Siebert (1987)"},"character":{"@id":"http://purl.org/phenoscape/uuid/7326302b-73bd-4215-9edd-b9dc7b6dc3d4","label":"Absence of basihyal tooth plate"},"phenotype":{"@id":"http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001648%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001648%3E%29","label":"basihyal tooth plate absent"},"@id":"http://purl.org/phenoscape/uuid/f8a70d93-5a2c-4d62-a973-5b86fd2fbb18"},{"description":"Absence of epibranchial I and II uncinate processes: present","matrix":{"@id":"http://www.worldcat.org/oclc/612613233","label":"Siebert (1987)"},"character":{"@id":"http://purl.org/phenoscape/uuid/b6b0020e-8b4b-450d-b7f0-cfc466d4687d","label":"Absence of epibranchial I and II uncinate processes"},"phenotype":{"@id":"http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001796%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001796%3E%29","label":"epibranchial 2 bone uncinate process absent"},"@id":"http://purl.org/phenoscape/uuid/1400f2a4-4aa4-466d-83a1-e79c060170d8"},{"description":"Absence of epibranchial I and II uncinate processes: present","matrix":{"@id":"http://www.worldcat.org/oclc/612613233","label":"Siebert (1987)"},"character":{"@id":"http://purl.org/phenoscape/uuid/b6b0020e-8b4b-450d-b7f0-cfc466d4687d","label":"Absence of epibranchial I and II uncinate processes"},"phenotype":{"@id":"http://purl.org/phenoscape/expression?value=%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002000%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E%29%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002503%3E+value+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001797%3E%29%29%29%0A+and+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2001797%3E%29","label":"epibranchial 1 bone uncinate process absent"},"@id":"http://purl.org/phenoscape/uuid/1400f2a4-4aa4-466d-83a1-e79c060170d8"}]}
```
***
Results from the old and new KB seem to be broadly in sync.

**Review by balhoff — APPROVED** [review]
I think this looks correct, but you may want to test with a more interesting anatomical structure (rather than 'multicellular organism'). I would try something like 'fin'.

**Comment by Shalsh23** [comment]
Test 3:
taxon: http://purl.obolibrary.org/obo/VTO_0064719
entity: http://purl.obolibrary.org/obo/UBERON_0008897
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0064719&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 71
}
```

New KB:
```
curl -X GET "http://localhost:8082/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0064719&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":70}
```

**Comment by Shalsh23** [comment]
Test 4:
taxon: http://purl.obolibrary.org/obo/VTO_0042308
entity: http://purl.obolibrary.org/obo/UBERON_0008897
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0042308&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 6
}
```

New KB:
```
curl -X GET "http://localhost:8082/entity/presence/evidence?taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0042308&entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":6}
```

Also matched the results by setting `total = false`, and they seem to be in sync.

**Pull request merged**
