### PR TITLE
Update taxon/annotations service to work with relation graphs

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Test 1:
entity: _
quality: _
in_taxon: _
phenotype: _
publication: _
parts: false
historical_homologs: false
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 809892
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/annotations?parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":818830}
```

**Comment by Shalsh23** [comment]
Test 2:
entity: http://purl.obolibrary.org/obo/UBERON_0008897
quality: http://purl.org/phenoscape/vocab.owl#inferred_presence
in_taxon: _
phenotype: _
publication: _
parts: false
historical_homologs: false
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 81079
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":82164}
```

**Comment by Shalsh23** [comment]
Test 3:

entity: http://purl.obolibrary.org/obo/UBERON_0008897
quality: http://purl.obolibrary.org/obo/PATO_0001995
in_taxon: _
phenotype: _
publication: _
parts: false
historical_homologs: false
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 5
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

**Comment by Shalsh23** [comment]
Test 4:

```
Setting `true=false` for Test 3.
```
entity: http://purl.obolibrary.org/obo/UBERON_0008897
quality: http://purl.obolibrary.org/obo/PATO_0001995
in_taxon: _
phenotype: _
publication: _
parts: false
historical_homologs: false
serial_homologs: _
limit: 20
offset: 0
total: false

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=false" -H "accept: application/json"
```
```
{
  "results": [
    {
      "taxon": {
        "@id": "http://purl.obolibrary.org/obo/VTO_9030086",
        "label": "Damocles"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002451%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4200023%3E%29%29",
        "label": "anterior dorsal fin sexually dimorphic"
      }
    },
    {
      "taxon": {
        "@id": "http://purl.obolibrary.org/obo/VTO_9022834",
        "label": "Echinochimaera snyderi"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002451%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4200023%3E%29%29",
        "label": "anterior dorsal fin sexually dimorphic"
      }
    },
    {
      "taxon": {
        "@id": "http://purl.obolibrary.org/obo/VTO_9013371",
        "label": "Falcatus"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002451%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4200023%3E%29%29",
        "label": "anterior dorsal fin sexually dimorphic"
      }
    },
    {
      "taxon": {
        "@id": "http://purl.obolibrary.org/obo/VTO_0033671",
        "label": "Hiodontidae"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002451%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4000163%3E%29%29",
        "label": "anal fin sexually dimorphic"
      }
    },
    {
      "taxon": {
        "@id": "http://purl.obolibrary.org/obo/VTO_9029943",
        "label": "Stethacanthus altonensis"
      },
      "phenotype": {
        "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002451%3E%0A+++++and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_4200023%3E%29%29",
        "label": "anterior dorsal fin sexually dimorphic"
      }
    }
  ]
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/annotations?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=false" -H "accept: application/json"
```
```
{"results":[]}
```

**Comment by balhoff** [comment]
This one (last example) works for me—I think your empty results might be a config mixup (hard to keep straight!).

**Comment by Shalsh23** [comment]
> This one (last example) works for me—I think your empty results might be a config mixup (hard to keep straight!).

Ah... Somehow this worked for me too now, even though the DB endpoint was correctly set and I didn't need to change the config. It must be something else I missed. So, should I go ahead and merge it?

**Comment by hlapp** [comment]
FYI, the tests that are marked as "passed" are from December. I guess there aren't real tests being run anyway right now, so maybe a passed test doesn't signify much more than no test, but you may need to think about migrating off of Travis-CI.org, which shut down at the end of 2020.

**Comment by Shalsh23** [comment]
> FYI, the tests that are marked as "passed" are from December. I guess there aren't real tests being run anyway right now, so maybe a passed test doesn't signify much more than no test, but you may need to think about migrating off of Travis-CI.org, which shut down at the end of 2020.

Oh, thanks for letting me know. We'll work on migrating off Travis-CI. But these tests that we are discussing above aren't the ones being run by Travis, but rather Test 1-4 detailed above, that we run manually on the local server over the new version of DB, and match the results against the currently deployed DB from swagger API.

**Pull request merged**
