### PR TITLE
Update taxon-with-phenotype service to work with relation graphs

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Test 1:
entity: _
quality: _
in_taxon: _
phenotype: _
parts: false
historical_homologs: false
serial_homologs: false
limit: 20
offset: 0
total: false

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/with_phenotype?parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=false" -H "accept: application/json"
```
```
{
  "results": [
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0039086",
      "label": "Abramis brama"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0064719",
      "label": "Abramites hypselonotus"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0064718",
      "label": "Abramites sp. (Fink and Fink 1981)"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0052709",
      "label": "Abyssocottidae"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0059975",
      "label": "Acanthicus hystrix"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0004767",
      "label": "Acanthixalus spinosus"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0064404",
      "label": "Acanthobrama hulensis"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0059348",
      "label": "Acanthobunocephalus nicoi"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0065027",
      "label": "Acanthocharax microlepis"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0061854",
      "label": "Acanthocleithron chapini"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0041218",
      "label": "Acanthocobitis botia"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0062793",
      "label": "Acanthocobitis sp. (Conway and Mayden 2007)"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_9014762",
      "label": "Acanthodidae"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_9011043",
      "label": "Acanthodii"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0041711",
      "label": "Acanthomorpha"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0069804",
      "label": "Acanthopleurus collettei"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0069803",
      "label": "Acanthopleurus serratus"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0069805",
      "label": "Acanthopleurus trispinosus"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0055692",
      "label": "Acanthopsetta nadeshnyi"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/VTO_0063018",
      "label": "Acanthopsoides delphax"
    }
  ]
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/with_phenotype?parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=false" -H "accept: application/json"
```
```
{"results":[{"@id":"http://purl.obolibrary.org/obo/VTO_0039086","label":"Abramis brama"},{"@id":"http://purl.obolibrary.org/obo/VTO_0064719","label":"Abramites hypselonotus"},{"@id":"http://purl.obolibrary.org/obo/VTO_0064718","label":"Abramites sp. (Fink and Fink 1981)"},{"@id":"http://purl.obolibrary.org/obo/VTO_0052709","label":"Abyssocottidae"},{"@id":"http://purl.obolibrary.org/obo/VTO_0059975","label":"Acanthicus hystrix"},{"@id":"http://purl.obolibrary.org/obo/VTO_0004767","label":"Acanthixalus spinosus"},{"@id":"http://purl.obolibrary.org/obo/VTO_0064404","label":"Acanthobrama hulensis"},{"@id":"http://purl.obolibrary.org/obo/VTO_0059348","label":"Acanthobunocephalus nicoi"},{"@id":"http://purl.obolibrary.org/obo/VTO_0065027","label":"Acanthocharax microlepis"},{"@id":"http://purl.obolibrary.org/obo/VTO_0061854","label":"Acanthocleithron chapini"},{"@id":"http://purl.obolibrary.org/obo/VTO_0041218","label":"Acanthocobitis botia"},{"@id":"http://purl.obolibrary.org/obo/VTO_0062793","label":"Acanthocobitis sp. (Conway and Mayden 2007)"},{"@id":"http://purl.obolibrary.org/obo/VTO_9014762","label":"Acanthodidae"},{"@id":"http://purl.obolibrary.org/obo/VTO_9011043","label":"Acanthodii"},{"@id":"http://purl.obolibrary.org/obo/VTO_0041711","label":"Acanthomorpha"},{"@id":"http://purl.obolibrary.org/obo/VTO_0069804","label":"Acanthopleurus collettei"},{"@id":"http://purl.obolibrary.org/obo/VTO_0069803","label":"Acanthopleurus serratus"},{"@id":"http://purl.obolibrary.org/obo/VTO_0069805","label":"Acanthopleurus trispinosus"},{"@id":"http://purl.obolibrary.org/obo/VTO_0055692","label":"Acanthopsetta nadeshnyi"},{"@id":"http://purl.obolibrary.org/obo/VTO_0063018","label":"Acanthopsoides delphax"}]}
```

**Comment by Shalsh23** [comment]
Test 2:
entity: <http://purl.obolibrary.org/obo/UBERON_0000468>
quality: <http://purl.org/phenoscape/vocab.owl#inferred_presence>
in_taxon: _
phenotype: _
parts: true
historical_homologs: true
serial_homologs: true
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&parts=true&historical_homologs=true&serial_homologs=true&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 6198
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&parts=true&historical_homologs=true&serial_homologs=true&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

**Comment by Shalsh23** [comment]
Test 3:
entity: http://purl.obolibrary.org/obo/UBERON_0000468
quality: http://purl.org/phenoscape/vocab.owl#inferred_presence
in_taxon: _
phenotype: _
parts: false
historical_homologs: false
serial_homologs: false
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 6198
}
```

New KB:
```
 curl -X GET "http://localhost:8082/taxon/with_phenot
ype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&part
s=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

**Comment by Shalsh23** [comment]
This service needs updates made to the `taxon/phenotype` service as well. These tests should be run after merging this branch into the `taxon-phenotype-update` branch.

**Comment by Shalsh23** [comment]
Test 3:
entity: http://purl.obolibrary.org/obo/UBERON_0000061
quality: http://purl.org/phenoscape/vocab.owl#inferred_presence
in_taxon: _
phenotype: _
parts: false
historical_homologs: false
serial_homologs: false
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000061%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 6198
}
```

New KB:
```
curl -X GET "http://localhost:8082/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000061%3E&quality=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence%3E&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

**Review by balhoff — APPROVED** [review]

**Pull request merged**
