### PR TITLE
Bug fix; rewrite query using sparql interpolator

### LINKED ISSUE #342: gene phenotypic profile service not working
In the `services-new-data-model` branch, the service to return a gene phenotypic profile is not working:

https://github.com/phenoscape/phenoscape-kb-services/blob/7cb76951bcd504444c25f2b04d21dfb395bbbc02/src/main/scala/org/phenoscape/kb/Gene.scala#L228-L248

No results are returned for `http://www.informatics.jax.org/accession/MGI:1917115`, although it does have phenotypes.

### PR DESCRIPTION
**Pull request by Shalsh23**
Closes #342

### CODE REVIEW

**Comment by Shalsh23** [comment]
These are the results being returned now:
```
{"results":[{"@id":"http://purl.obolibrary.org/obo/MP_0009642","label":"abnormal blood homeostasis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002139","label":"abnormal hepatobiliary system physiology","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005329","label":"abnormal myocardium layer morphology","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0009643","label":"abnormal urine homeostasis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005140","label":"decreased cardiac muscle contractility","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0000352","label":"decreased cell proliferation","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005560","label":"decreased circulating glucose level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002727","label":"decreased circulating insulin level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0003458","label":"decreased circulating ketone body level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0013278","label":"decreased fasting circulating glucose level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0009356","label":"decreased liver triglyceride level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0003402","label":"decreased liver weight","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005659","label":"decreased susceptibility to diet-induced obesity","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0011424","label":"decreased urine uric acid level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002795","label":"dilated cardiomyopathy","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0011094","label":"embryonic lethality before implantation, complete penetrance","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005376","label":"homeostasis/metabolism phenotype","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0030973","label":"impaired gluconeogenesis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005292","label":"improved glucose tolerance","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005178","label":"increased circulating cholesterol level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0001552","label":"increased circulating triglyceride level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002891","label":"increased insulin sensitivity","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0010400","label":"increased liver glycogen level","sources":[]}]}
```
vs the results being returned by the currently deployed version of the service as below:
```
{
  "results": [
    {
      "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0001205%3E%29%29",
      "label": "Meckel's cartilage shape",
      "sources": [
        {
          "@id": "http://zfin.org/ZDB-FIG-080929-13"
        },
        {
          "@id": "http://zfin.org/ZDB-FIG-080604-23"
        }
      ]
    },
    {
      "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001483%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0000316%3E%29%29",
      "label": "basihyal bone aplastic",
      "sources": [
        {
          "@id": "http://zfin.org/ZDB-FIG-080604-35"
        },
        {
          "@id": "http://zfin.org/ZDB-FIG-080604-30"
        },
        {
          "@id": "http://zfin.org/ZDB-FIG-080929-13"
        }
      ]
    }
  ]
}
```

**Review by balhoff — CHANGES_REQUESTED** [review]
Just want to check — are the example results being returned for a different gene in the query? Or it is supposed to be the same?

Also, can you look into why nothing is returned for `sources`? I wonder if it is a difference in the `dc` namespace being used (there are two that get confused).

**Comment by Shalsh23** [comment]
> These are the results are for `http://www.informatics.jax.org/accession/MGI:1917115` for `https://stars-app.renci.org/phenoscape-dev/sparql` endpoint.
> 
> ```
> {"results":[{"@id":"http://purl.obolibrary.org/obo/MP_0009642","label":"abnormal blood homeostasis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002139","label":"abnormal hepatobiliary system physiology","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005329","label":"abnormal myocardium layer morphology","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0009643","label":"abnormal urine homeostasis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005140","label":"decreased cardiac muscle contractility","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0000352","label":"decreased cell proliferation","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005560","label":"decreased circulating glucose level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002727","label":"decreased circulating insulin level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0003458","label":"decreased circulating ketone body level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0013278","label":"decreased fasting circulating glucose level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0009356","label":"decreased liver triglyceride level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0003402","label":"decreased liver weight","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005659","label":"decreased susceptibility to diet-induced obesity","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0011424","label":"decreased urine uric acid level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002795","label":"dilated cardiomyopathy","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0011094","label":"embryonic lethality before implantation, complete penetrance","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005376","label":"homeostasis/metabolism phenotype","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0030973","label":"impaired gluconeogenesis","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005292","label":"improved glucose tolerance","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0005178","label":"increased circulating cholesterol level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0001552","label":"increased circulating triglyceride level","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0002891","label":"increased insulin sensitivity","sources":[]},{"@id":"http://purl.obolibrary.org/obo/MP_0010400","label":"increased liver glycogen level","sources":[]}]}
> ```
> 
> vs the results being returned by the currently deployed version of the service as below are for `http://www.informatics.jax.org/marker/MGI:1917115` IRI, for `https://stars-app.renci.org/phenoscape/sparql` endpoint.
> 
> ```
> {
>   "results": [
>     {
>       "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0001205%3E%29%29",
>       "label": "Meckel's cartilage shape",
>       "sources": [
>         {
>           "@id": "http://zfin.org/ZDB-FIG-080929-13"
>         },
>         {
>           "@id": "http://zfin.org/ZDB-FIG-080604-23"
>         }
>       ]
>     },
>     {
>       "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%0A++++%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001483%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0000316%3E%29%29",
>       "label": "basihyal bone aplastic",
>       "sources": [
>         {
>           "@id": "http://zfin.org/ZDB-FIG-080604-35"
>         },
>         {
>           "@id": "http://zfin.org/ZDB-FIG-080604-30"
>         },
>         {
>           "@id": "http://zfin.org/ZDB-FIG-080929-13"
>         }
>       ]
>     }
>   ]
> }
> ```

**Comment by Shalsh23** [comment]
IRI: `http://www.informatics.jax.org/accession/MGI:1917115`
Endpoint: `https://stars-app.renci.org/phenoscape-dev/sparql`

Latest results: 
```
{"results":[{"@id":"http://purl.obolibrary.org/obo/MP_0009642","label":"abnormal blood homeostasis","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0002139","label":"abnormal hepatobiliary system physiology","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005329","label":"abnormal myocardium layer morphology","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/19520971"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0009643","label":"abnormal urine homeostasis","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005140","label":"decreased cardiac muscle contractility","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/19520971"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0000352","label":"decreased cell proliferation","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/16055734"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005560","label":"decreased circulating glucose level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0002727","label":"decreased circulating insulin level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0003458","label":"decreased circulating ketone body level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0013278","label":"decreased fasting circulating glucose level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0009356","label":"decreased liver triglyceride level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0003402","label":"decreased liver weight","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005659","label":"decreased susceptibility to diet-induced obesity","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0011424","label":"decreased urine uric acid level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0002795","label":"dilated cardiomyopathy","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/19520971"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0011094","label":"embryonic lethality before implantation, complete penetrance","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/16055734"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005376","label":"homeostasis/metabolism phenotype","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0030973","label":"impaired gluconeogenesis","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005292","label":"improved glucose tolerance","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0005178","label":"increased circulating cholesterol level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0001552","label":"increased circulating triglyceride level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0002891","label":"increased insulin sensitivity","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]},{"@id":"http://purl.obolibrary.org/obo/MP_0010400","label":"increased liver glycogen level","sources":[{"@id":"http://www.ncbi.nlm.nih.gov/pubmed/31597092"}]}]}
```

**Review by balhoff — APPROVED** [review]

**Pull request merged**
