### PR TITLE
Update study/query service to work with relation graphs

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Test 1:
entity: http://purl.obolibrary.org/obo/UBERON_0008897
quality: http://purl.org/phenoscape/vocab.owl#inferred_presence
in_taxon: _
phenotype: _
publication: _
parts: _
historical_homologs: _
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 167
}
```

New KB:
```
curl -X GET "http://localhost:8082/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":189}
```

**Comment by Shalsh23** [comment]
Test 2:
entity: http://purl.obolibrary.org/obo/UBERON_0008897
quality: http://purl.org/phenoscape/vocab.owl#inferred_absence
in_taxon: _
phenotype: _
publication: _
parts: _
historical_homologs: _
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_absence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 134
}
```

New KB:
```
curl -X GET "http://localhost:8082/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_absence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

**Comment by Shalsh23** [comment]
Test 3:
entity: http://purl.obolibrary.org/obo/UBERON_0000970
quality: http://purl.org/phenoscape/vocab.owl#inferred_absence
in_taxon: _
phenotype: _
publication: _
parts: _
historical_homologs: _
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 40
}
```

New KB:
```
curl -X GET "http://localhost:8082/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_presence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":50}
```

**Comment by Shalsh23** [comment]
Test 4:
entity: http://purl.obolibrary.org/obo/UBERON_0000970
quality: http://purl.org/phenoscape/vocab.owl#inferred_absence
in_taxon: _
phenotype: _
publication: _
parts: _
historical_homologs: _
serial_homologs: _
limit: 20
offset: 0
total: true

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_absence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 26
}
```

New KB:
```
curl -X GET "http://localhost:8082/study/query?entity=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&quality=http%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23inferred_absence&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":1}
```

**Comment by balhoff** [comment]
I pushed a commit to fix the remaining issue here.

**Review by balhoff — APPROVED** [review]

**Pull request merged**
