### PR TITLE
Reorganize design of Term classes

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
> There are compiler errors—did you want me to look into those, or can you fix first?

No, I am working on resolving the errors. There is no way to `unsend` the review request here 😬 .

**Comment by balhoff** [comment]
Got it!

**Comment by Shalsh23** [comment]
@balhoff I couldn't resolve some design contradictions that are cropping up. Will need to discuss with you.

**Comment by balhoff** [comment]
Moved to #214.

**Pull request closed without merging**
