### PR TITLE
Update similarity/profile_size service to work with relation graphs

### LINKED ISSUE #410: Update profile size service to use property path input
Something like this for input path `has_character/has_state/describes_phenotype`:

```sparql
SELECT (COUNT(DISTINCT ?phen) AS ?count) 
WHERE {
?item has_character/has_state/describes_phenotype ?phen .
}
```

### PR DESCRIPTION
**Pull request by Shalsh23**
Closes #410

### CODE REVIEW

**Comment by Shalsh23** [comment]
Test 1:

iri: ` http://purl.obolibrary.org/obo/VTO_0041711`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/similarity/profile_size?iri=%20http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0041711" -H "accept: application/json"
```
```
{
  "total": 151
}
```

New KB:
path: `<http://purl.org/phenoscape/vocab.owl#exhibits_state>/<http://purl.org/phenoscape/vocab.owl#describes_phenotype>`

```
curl -X GET "http://localhost:8082/similar
ity/profile_size?iri=%20http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0041711&path=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23exhibits_state
%3E%2F%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23describes_phenotype%3E" -H "accept: application/json"
```
```
{"total":14}
```

**Comment by Shalsh23** [comment]
Test 2:

iri: `<http://www.informatics.jax.org/marker/MGI:1917115>`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/similarity/profile_size?iri=http%3A%2F%2Fwww.informatics.jax.org%2Fmarker%2FMGI%3A1917115" -H "accept: application/json"
```
```
{
  "total": 2
}
```

New KB:
```
curl -X GET "http://localhost:8082/similarity/profile_size?iri=http%3A%2F%2Fwww.informatics.jax.org%2Fmarker%2FMGI%3A1917115&path=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23has_phenotypic_profile%3E%2F%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E" -H "accept: application/json"
```
```
{"total":0}
```

**Comment by balhoff** [comment]
MGI genes have a different IRI structure in the new data: `http://www.informatics.jax.org/accession/MGI:1917115`

**Comment by Shalsh23** [comment]
Test 3:

iri: `http://zfin.org/ZDB-GENE-030131-9790`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/similarity/profile_size?iri=http%3A%2F%2Fzfin.org%2FZDB-GENE-030131-9790" -H "accept: application/json"
```
```
{
  "total": 6
}
```

New KB:

path: `<http://purl.org/phenoscape/vocab.owl#has_phenotypic_profile>/rdf:type`

```
curl -X GET "http://localhost:8082/similarity/profile_size?iri=http%3A%2F%2Fzfin.org%2FZDB-GENE-030131-9790&path=%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23has_phenotypic_profile%3E%2F%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E" -H "accept: application/json"
```
```
{"total":78}
```

**Review by balhoff — APPROVED** [review]

**Pull request merged**
